import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="min-h-screen w-screen">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-screen flex flex-col`}
        >
          <header className="flex justify-between items-center px-6 h-16 border-b border-gray-700 bg-gradient-to-r from-[#1a1a1a] to-[#0d0d0d]">
  {/* Left side: App Logo */}
 <span
  className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600 
             font-extrabold text-lg sm:text-2xl tracking-wide 
             transform transition-transform duration-300 hover:scale-105 animate-pulse"
>
  PDF-CHATBOT
</span>

  {/* Right side: Auth Buttons or User Button */}
  <div className="flex items-center gap-4">
    <SignedOut>
      <SignInButton />
      <SignUpButton>
        <button className="bg-[#6c47ff] hover:bg-[#5a3bcc] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-11 px-4 sm:px-6 shadow-md transition-all">
          Sign Up
        </button>
      </SignUpButton>
    </SignedOut>

    <SignedIn>
      <UserButton />
    </SignedIn>
  </div>
</header>

          
            {children}
          
        </body>
      </html>
    </ClerkProvider>
  );
}